config/routes.rb
Expenses::Application.routes.draw do
  resources :returns

    get "import_histories/:id" => "import_histories#show"
    get "import_histories" => "import_histories#index"
    delete "import_histories/delete_imported_records" => "import_histories#delete_imported_records"

    get "payment_notes/create"

    root :to => 'expenses#menu'

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    resources :users
    resources :sessions
    resources :groups

    get "menu" => "expenses#menu", :as => 'menu'
    get "expenses/import" => "expenses#import", :as => 'import'
    get "expenses/process_imports" => "expenses#process_imports", :as => 'process_imports'
    get "expenses/process_data" => "expenses#process_data", :as => 'process_data'
    match 'expenses/process_import/:id' => 'expenses#process_import'
    post "expenses/import" => "expenses#file_upload"
    post "expenses/add_imported_expenses" => "expenses#add_imported_expenses"
    post "expenses/create_from_imported" => "expenses#create_from_imported"
    post "expenses/process_all_now" => "expenses#process_all_now"

    get "user_payments/approve" => "user_payments#approve"
    post "user_payments/approve_payment" => "user_payments#approve_payment"

    post "user_payments/add_note" => "user_payments#add_note"
    delete "user_payments/remove_note" => "user_payments#remove_note"

    get "stores/parents"
    post "stores/save_parents"

    resources :expenses
    resources :user_payments
    resources :pay_methods
    resources :reasons
    resources :stores

end

app/models/group.rb
class Group < ActiveRecord::Base
    include SharedMethods

    # Accessible attributes
    attr_accessible :name, :description, :display_order, :hidden

    # Relationships
    has_many :expenses
    has_many :group_members
    has_many :users, :through => :group_members

    # Before validations
    before_validation :set_app_version

    # Validations
    validates :name, :presence => true, :uniqueness => {:case_sensitive => false}, :length => {:maximum => 50}
    validates :app_version, :presence => true

    # Callbacks
    before_destroy :check_for_users

    # Method to add user to group
    def add_user(user)
	# Get user groups
	user_groups=user.groups
	# check if user already a member
	if user_groups.detect{|g| g.name == self.name}
	    # Add error
	    self.errors.add(:base,"User #{user.user_name} is already a member of group #{self.name}")
	    # Return value
	    return false
	else
	    # Prepare group_membership attributes
	    attr={:user_id => user.id, :group_id => self.id}
	    # Create a group_membership entry
	    GroupMember.create!(attr)
	    # Return value
	    return true
	end
    end

    # Methods below are private
    private

    # Method to check for users
    def check_for_users
	if self.users.size > 0
	    self.errors.add(:base,"Can't delete #{self.class} '#{self.name}' because this group has existing users")
	    return false
	else
	    return true
	end
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  -if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :display_order
    = f.number_field :display_order
  .actions
    = f.submit 'Save'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

%table
  %tr
    %th Name
    %th Description
    %th Display order
    %th
    %th
    %th

  - @groups.each do |group|
    %tr
      %td= group.name
      %td= group.description
      %td= group.display_order
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Description:
  = @group.description
%p
  %b Display order:
  = @group.display_order

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path