config/routes.rb
Expenses::Application.routes.draw do
  resources :returns

    get "import_histories/:id" => "import_histories#show"
    get "import_histories" => "import_histories#index"
    delete "import_histories/delete_imported_records" => "import_histories#delete_imported_records"

    get "payment_notes/create"

    root :to => 'expenses#menu'

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    resources :users
    resources :sessions
    resources :groups

    get "menu" => "expenses#menu", :as => 'menu'
    get "expenses/import" => "expenses#import", :as => 'import'
    get "expenses/process_imports" => "expenses#process_imports", :as => 'process_imports'
    get "expenses/process_data" => "expenses#process_data", :as => 'process_data'
    match 'expenses/process_import/:id' => 'expenses#process_import'
    post "expenses/import" => "expenses#file_upload"
    post "expenses/add_imported_expenses" => "expenses#add_imported_expenses"
    post "expenses/create_from_imported" => "expenses#create_from_imported"
    post "expenses/process_all_now" => "expenses#process_all_now"

    get "user_payments/approve" => "user_payments#approve"
    post "user_payments/approve_payment" => "user_payments#approve_payment"

    post "user_payments/add_note" => "user_payments#add_note"
    delete "user_payments/remove_note" => "user_payments#remove_note"

    get "stores/parents"
    post "stores/save_parents"

    resources :expenses
    resources :user_payments
    resources :pay_methods
    resources :reasons
    resources :stores

end

app/models/reason.rb
class Reason < ActiveRecord::Base
    include SharedMethods

    # Accessible attributes
    attr_accessible :name

    # Relationships
    has_many :expenses

    # Before validations
    before_validation :set_app_version

    # Validations
    validates :name, :presence => true, :uniqueness => {:case_sensitive => false}, :length => {:maximum => 50}
    validates :app_version, :presence => true

    # Before actions
    # see observer check_for_expenses_observer.rb
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
    before_filter :login_required
    # GET /reasons
    # GET /reasons.json
    def index
	@reasons = Reason.all

	respond_to do |format|
	    format.html # index.html.erb
	    format.json { render json: @reasons }
	end
    end

    # GET /reasons/1
    # GET /reasons/1.json
    def show
	@reason = Reason.find(params[:id])

	respond_to do |format|
	    format.html # show.html.erb
	    format.json { render json: @reason }
	end
    end

    # GET /reasons/new
    # GET /reasons/new.json
    def new
	@reason = Reason.new
	@reasons = Reason.order('name').all

	respond_to do |format|
	    format.html # new.html.erb
	    format.json { render json: @reason }
	end
    end

    # GET /reasons/1/edit
    def edit
	@reason = Reason.find(params[:id])
    end

    # POST /reasons
    # POST /reasons.json
    def create
	@reason = Reason.new(params[:reason])

	respond_to do |format|
	    if @reason.save
		# Get previous expense
		expense=session[:current_expense]
		# Set new reason
		if not expense.nil?
		    expense.reason_id=@reason.id
		    session[:current_expense]=expense
		end
		format.html { redirect_to "#{expenses_path}/new", notice: 'Reason was successfully created.' }
		format.json { render json: @reason, status: :created, location: @reason }
	    else
		@reasons = Reason.order('name').all
		format.html { render action: "new" }
		format.json { render json: @reason.errors, status: :unprocessable_entity }
	    end
	end
    end

    # PUT /reasons/1
    # PUT /reasons/1.json
    def update
	@reason = Reason.find(params[:id])

	respond_to do |format|
	    if @reason.update_attributes(params[:reason])
		format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
		format.json { head :ok }
	    else
		format.html { render action: "edit" }
		format.json { render json: @reason.errors, status: :unprocessable_entity }
	    end
	end
    end

    # DELETE /reasons/1
    # DELETE /reasons/1.json
    def destroy
	@reason = Reason.find(params[:id])
	@reason.destroy

	respond_to do |format|
	    format.html { redirect_to reasons_url }
	    format.json { head :ok }
	end
    end
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_form.html.haml
= form_for @reason do |f|
  -if @reason.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reason.errors.count, "error")} prohibited this reason from being saved:"
      %ul
        - @reason.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'
%hr
%h2
  Existing Pay Methods:
  %ul
    - @reasons.each do |p|
      %li
        = p.name

app/views/reasons/edit.html.haml
%h1 Editing reason

= render 'form'

= link_to 'Show', @reason
\|
= link_to 'Back', reasons_path

app/views/reasons/index.html.haml
%h1 Listing reasons

%table
  %tr
    %th Reason
    %th
    %th
    %th

  - @reasons.each do |reason|
    %tr
      %td= reason.reason
      %td= link_to 'Show', reason
      %td= link_to 'Edit', edit_reason_path(reason)
      %td= link_to 'Destroy', reason, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Reason', new_reason_path

app/views/reasons/new.html.haml
%h1 New reason

= render 'form'

app/views/reasons/show.html.haml
%p#notice= notice

%p
  %b Reason:
  = @reason.reason

= link_to 'Edit', edit_reason_path(@reason)
\|
= link_to 'Back', reasons_path