config/routes.rb
Expenses::Application.routes.draw do
  resources :returns

    get "import_histories/:id" => "import_histories#show"
    get "import_histories" => "import_histories#index"
    delete "import_histories/delete_imported_records" => "import_histories#delete_imported_records"

    get "payment_notes/create"

    root :to => 'expenses#menu'

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    resources :users
    resources :sessions
    resources :groups

    get "menu" => "expenses#menu", :as => 'menu'
    get "expenses/import" => "expenses#import", :as => 'import'
    get "expenses/process_imports" => "expenses#process_imports", :as => 'process_imports'
    get "expenses/process_data" => "expenses#process_data", :as => 'process_data'
    match 'expenses/process_import/:id' => 'expenses#process_import'
    post "expenses/import" => "expenses#file_upload"
    post "expenses/add_imported_expenses" => "expenses#add_imported_expenses"
    post "expenses/create_from_imported" => "expenses#create_from_imported"
    post "expenses/process_all_now" => "expenses#process_all_now"

    get "user_payments/approve" => "user_payments#approve"
    post "user_payments/approve_payment" => "user_payments#approve_payment"

    post "user_payments/add_note" => "user_payments#add_note"
    delete "user_payments/remove_note" => "user_payments#remove_note"

    get "stores/parents"
    post "stores/save_parents"

    resources :expenses
    resources :user_payments
    resources :pay_methods
    resources :reasons
    resources :stores

end

app/models/pay_method.rb
class PayMethod < ActiveRecord::Base
    include SharedMethods

    # Accessible attributes
    attr_accessible :name

    # Relationships
    has_many :expenses

    # Before validations
    before_validation :set_app_version

    # Validations
    validates :name, :presence => true, :uniqueness => {:case_sensitive => false}, :length => {:maximum => 50}
    validates :app_version, :presence => true

    # Before actions
    # see observer check_for_expenses_observer.rb
end

app/controllers/pay_methods_controller.rb
class PayMethodsController < ApplicationController
    before_filter :login_required

    # GET /pay_methods
    # GET /pay_methods.json
    def index
	@pay_methods = PayMethod.all

	respond_to do |format|
	    format.html # index.html.erb
	    format.json { render json: @pay_methods }
	end
    end

    # GET /pay_methods/1
    # GET /pay_methods/1.json
    def show
	@pay_method = PayMethod.find(params[:id])

	respond_to do |format|
	    format.html # show.html.erb
	    format.json { render json: @pay_method }
	end
    end

    # GET /pay_methods/new
    # GET /pay_methods/new.json
    def new
	@pay_method = PayMethod.new
	@pay_methods = PayMethod.order('name').all

	respond_to do |format|
	    format.html # new.html.erb
	    format.json { render json: @pay_method }
	end
    end

    # GET /pay_methods/1/edit
    def edit
	@pay_method = PayMethod.find(params[:id])
    end

    # POST /pay_methods
    # POST /pay_methods.json
    def create
	@pay_method = PayMethod.new(params[:pay_method])

	respond_to do |format|
	    if @pay_method.save
		# Get previous expense
		expense=session[:current_expense]
		# Set new pay method
		if not expense.nil?
		    expense.pay_method_id=@pay_method.id
		    session[:current_expense]=expense
		end
		format.html { redirect_to "#{expenses_path}/new", notice: 'Pay method was successfully created.' }
		format.json { render json: @pay_method, status: :created, location: @pay_method }
	    else
		@pay_methods = PayMethod.order('name').all
		format.html { render action: "new" }
		format.json { render json: @pay_method.errors, status: :unprocessable_entity }
	    end
	end
    end

    # PUT /pay_methods/1
    # PUT /pay_methods/1.json
    def update
	@pay_method = PayMethod.find(params[:id])

	respond_to do |format|
	    if @pay_method.update_attributes(params[:pay_method])
		format.html { redirect_to @pay_method, notice: 'Pay method was successfully updated.' }
		format.json { head :ok }
	    else
		format.html { render action: "edit" }
		format.json { render json: @pay_method.errors, status: :unprocessable_entity }
	    end
	end
    end

    # DELETE /pay_methods/1
    # DELETE /pay_methods/1.json
    def destroy
	@pay_method = PayMethod.find(params[:id])
	@pay_method.destroy

	respond_to do |format|
	    format.html { redirect_to pay_methods_url }
	    format.json { head :ok }
	end
    end
end

app/helpers/pay_methods_helper.rb
module PayMethodsHelper
end

app/views/pay_methods/_form.html.haml
= form_for @pay_method do |f|
  -if @pay_method.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pay_method.errors.count, "error")} prohibited this pay_method from being saved:"
      %ul
        - @pay_method.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'
%hr
%h2
  Existing Pay Methods:
  %ul
    - @pay_methods.each do |p|
      %li
        = p.name

app/views/pay_methods/edit.html.haml
%h1 Editing pay_method

= render 'form'

= link_to 'Show', @pay_method
\|
= link_to 'Back', pay_methods_path

app/views/pay_methods/index.html.haml
%h1 Listing pay_methods

%table
  %tr
    %th Pay method
    %th
    %th
    %th

  - @pay_methods.each do |pay_method|
    %tr
      %td= pay_method.pay_method
      %td= link_to 'Show', pay_method
      %td= link_to 'Edit', edit_pay_method_path(pay_method)
      %td= link_to 'Destroy', pay_method, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Pay method', new_pay_method_path

app/views/pay_methods/new.html.haml
%h1 New Pay Method

= render 'form'

app/views/pay_methods/show.html.haml
%p#notice= notice

%p
  %b Pay method:
  = @pay_method.pay_method

= link_to 'Edit', edit_pay_method_path(@pay_method)
\|
= link_to 'Back', pay_methods_path