config/routes.rb
Expenses::Application.routes.draw do
  resources :returns

    get "import_histories/:id" => "import_histories#show"
    get "import_histories" => "import_histories#index"
    delete "import_histories/delete_imported_records" => "import_histories#delete_imported_records"

    get "payment_notes/create"

    root :to => 'expenses#menu'

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    resources :users
    resources :sessions
    resources :groups

    get "menu" => "expenses#menu", :as => 'menu'
    get "expenses/import" => "expenses#import", :as => 'import'
    get "expenses/process_imports" => "expenses#process_imports", :as => 'process_imports'
    get "expenses/process_data" => "expenses#process_data", :as => 'process_data'
    match 'expenses/process_import/:id' => 'expenses#process_import'
    post "expenses/import" => "expenses#file_upload"
    post "expenses/add_imported_expenses" => "expenses#add_imported_expenses"
    post "expenses/create_from_imported" => "expenses#create_from_imported"
    post "expenses/process_all_now" => "expenses#process_all_now"

    get "user_payments/approve" => "user_payments#approve"
    post "user_payments/approve_payment" => "user_payments#approve_payment"

    post "user_payments/add_note" => "user_payments#add_note"
    delete "user_payments/remove_note" => "user_payments#remove_note"

    get "stores/parents"
    post "stores/save_parents"

    resources :expenses
    resources :user_payments
    resources :pay_methods
    resources :reasons
    resources :stores

end

app/models/user_payment.rb
class UserPayment < ActiveRecord::Base
    include SharedMethods

    # Accessible attributes
    attr_accessible :from_user_id, :to_user_id, :amount

    # Relationships
    has_many :payment_notes
    belongs_to :from_user, :class_name => 'User'
    belongs_to :to_user, :class_name => 'User' 
    belongs_to :waiting_on_user, :class_name => 'User' 
    belongs_to :update_balance_history
    belongs_to :return
    accepts_nested_attributes_for :payment_notes

    # Before validations
    before_validation :set_app_version
    before_validation :check_return_id

    # Validations
    validates :from_user, :presence => true
    validates :to_user, :presence => true
    validates :amount, :presence => true, :numericality => true
    validates :app_version, :presence => true
    # Custom validation
    validate :check_from_and_to
    validate :check_approve_fields
    validate :check_amount
    validate :validate_process_flag, :on => :create

    # Callbacks
    before_create :validate_not_approved, :check_approved_date, :set_waiting_on_user_id
    before_destroy :check_for_approval, :check_process_flag

    # Method to approve this user payment
    def approve(user_id)
	if user_id != self.to_user_id
	    # Error
	    errors.add(:base,"Error: Only to_user can approve user_payments.")
	    # Return
	    return false
	end
	# Set approved to true
	self.approved=true
	# Set approved_date
	self.approved_date=Time.now
	# Save record
	self.save!
    end

    # Method to show visible payment_notes (not deleted)
    def visible_payment_notes
	self.payment_notes.select{|pn| pn.deleted == false}
    end

    # Method to add a return payment (refund)
    def self.return_payment(return_payment_id, from_id, to_id, amount)
	# Create new UserPayment
	up=self.new()
	# Add attributes
	up.from_user_id=from_id
	up.to_user_id=to_id
	up.amount=amount
	up.return_id=return_payment_id
	# Save record
	up.save!
	# Set to approved because it's system doing the payment
	up.approved=true
	# Set approved_date
	up.approved_date=Time.now
	# Save record
	up.save!
	# Return id
	return up.id
    end

    # Private methods
    private

    # Method to make sure from and to are not the same
    def check_from_and_to
	if from_user_id == to_user_id
	    errors.add(:to_user, "can't be the same as from_user")
	end
    end

    # Method to make sure all approved fields are filled in
    def check_approve_fields
	# Get data
	approved_date_blank=approved_date.blank?
	# Make sure both approve fields are set
	if (approved == true and approved_date_blank == true) or (approved != true and not approved_date_blank)
	    errors.add(:base,"All approve fields must be filled")
	end
    end

    # Method to check for a negative amount
    def check_amount
	# Check for negative amount
	self.errors.add(:base,"Amount cannot be negative") if not self.amount.nil? and self.amount < 0
    end

    # Method to make sure approved is not set
    def validate_not_approved
	if self.approved
	    self.errors.add(:base,"Can't create #{self.class}, entry can't be approved on creation")
	    return false
	else
	    return true
	end
    end

    # Method to make sure approved_date is not set
    def check_approved_date
	if not self.approved_date.nil?
	    self.errors.add(:base,"Can't create #{self.class}, entry can't have an approved_date on creation")
	    return false
	else
	    return true
	end
    end

    # Method to check process flag
    def validate_process_flag
	# Add error if process_flag is true
	self.errors.add(:base,"Process_flag cannot be set to true on record creation") if self.process_flag == true
    end

    # Method to check approved
    def check_for_approval
	if self.approved == true
	    self.errors.add(:base,"Can't destroy #{self.class}, it's already been approved")
	    return false
	else
	    return true
	end
    end

    # Method to check process_flag
    def check_process_flag
	if self.process_flag == true
	    self.errors.add(:base,"Can't destroy #{self.class}, it's already been processed")
	    return false
	else
	    return true
	end
    end

    # Method to set initial waiting_on_user_id
    def set_waiting_on_user_id
	self.waiting_on_user_id = self.to_user_id
    end

    # Method to check parent id
    def check_return_id
	# Get return id
	return_id=self.return_id
	# If 0, OK since it is the default
	return true if return_id == 0
	# Check child
	if Return.where(:id => return_id).first
	    return true
	else
	    self.errors.add(:base,"Can't create #{self.class}: because it references a non-existing Return")
	    return false
	end
    end
end

app/controllers/user_payments_controller.rb
class UserPaymentsController < ApplicationController
    before_filter :login_required

  # GET /user_payments
  # GET /user_payments.json
  def index
    @user_payments = UserPayment.includes(:from_user).includes(:to_user).where("from_user_id = ? or to_user_id = ?",current_user.id,current_user.id).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_payments }
    end
  end

  # GET /user_payments/1
  # GET /user_payments/1.json
  def show
    @user_payment = UserPayment.includes(:from_user).includes(:to_user).includes(:payment_notes).find(params[:id])
    @payment_note = PaymentNote.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_payment }
    end
  end

  # GET /user_payments/new
  # GET /user_payments/new.json
  def new
      # Get objects
    @user_payment = UserPayment.new
    @users=User.where("id <> ?",current_user.id).where(:hidden => false).all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_payment }
    end
  end

  # GET /user_payments/1/edit
  def edit
    @user_payment = UserPayment.find(params[:id])
    @users=User.where("id <> ?",current_user.id).where(:hidden => false).all
  end

  # POST /user_payments
  # POST /user_payments.json
  def create
    @user_payment = UserPayment.new(params[:user_payment])
    @payment_note = PaymentNote.new(params[:payment_note])
    @users=User.where("id <> ?",current_user.id).where(:hidden => false).all

    # Set defaults
    @user_payment.from_user_id=current_user.id

    respond_to do |format|
      if @user_payment.save
	  # Check if there is a note to save
	  if @payment_note.note.size > 0
	      # Reload
	      @user_payment.reload
	      # Set PaymentNote options
	      @payment_note.user_payment_id=@user_payment.id
	      @payment_note.user_id=current_user.id
	      # Save note
	      @payment_note.save!
	  end
        format.html { redirect_to menu_path, notice: 'User payment was successfully created.' }
        format.json { render json: @user_payment, status: :created, location: @user_payment }
      else
        format.html { render action: "new" }
        format.json { render json: @user_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_payments/1
  # PUT /user_payments/1.json
  def update
    @user_payment = UserPayment.find(params[:id])

    respond_to do |format|
      if @user_payment.update_attributes(params[:user_payment])
        format.html { redirect_to @user_payment, notice: 'User payment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_payments/1
  # DELETE /user_payments/1.json
  def destroy
    @user_payment = UserPayment.find(params[:id])
    @user_payment.destroy

    respond_to do |format|
      format.html { redirect_to user_payments_url }
      format.json { head :ok }
    end
  end

  # Add note
  def add_note
    @payment_note = PaymentNote.new(params[:payment_note])
    @user_payment = UserPayment.find(params[:user_payment_id])

    # Set PaymentNote options
    @payment_note.user_payment_id=@user_payment.id
    @payment_note.user_id=current_user.id

    respond_to do |format|
      if @payment_note.save
        format.html { redirect_to "/user_payments/#{@user_payment.id}", notice: 'Note successfully created.' }
      else
        format.html { render action: "show" }
      end
    end
  end

  # Remove note
  def remove_note
    @payment_note = PaymentNote.find(params[:id])
    @user_payment = @payment_note.user_payment

    respond_to do |format|
	if @payment_note.delete_note
	  format.html { redirect_to "/user_payments/#{@user_payment.id}", notice: 'Note successfully deleted' }
	  format.json { head :ok }
	else
	  format.html { redirect_to "/user_payments/#{@user_payment.id}", alert: "#{@payment_note.errors.messages.values.join(',')}" }
	end
    end
  end

  # Approve user payments
  def approve
      # Get records that need approval
      @user_payments=current_user.get_user_payments_waiting_for_approval
      # Go back to menu if none exist
      if @user_payments.size < 1
	  redirect_to menu_path and return
      end
  end

  # Method to approve payment
  def approve_payment
      # Get records that need approval
      user_payments=current_user.get_user_payments_waiting_for_approval
      # Get user_payment
      user_payment=UserPayment.find(params[:user_payment_id])
      # Get note
      note=params[:payment_approval][:note]
      # Get submit value
      submit=params[:commit]
      # Try to create note
      payment_note=PaymentNote.new(:note => note)
      payment_note.user_id=current_user.id
      payment_note.user_payment_id=user_payment.id
      # Check submit button
      if submit =~ /approve/i
	  # Aprove
	  if user_payment.approve(current_user.id)
	      redirect_to menu_path, notice: "Payment approved"
	  else
	      redirect_to "/user_payments/approve", alert: "Error: could not approve UserPayment id:#{user_payment.id}, #{user_payment.errors.full_messages}" and return
	  end
      elsif submit =~ /reject/i
	  # Check for note
	  if not payment_note.valid?
	      # Note required
	      redirect_to "/user_payments/approve", alert: "Error: could not reject UserPayment because a Note is required. Message: #{payment_note.errors.full_messages}" and return
	  end
	  # Bounce message back
	  user_payment.waiting_on_user_id=user_payment.from_user_id
	  # Save record
	  if user_payment.save
	      # Save note
	      payment_note.save!
	  end
	  # Notice
	  notice="Payment successfully rejected."
	  # Check if more user_payments
	  if user_payments.size > 0
	      # Redirect to approve
	      redirect_to "/user_payments/approve", notice: notice and return
	  else
	      # Redirect to menu
	      redirect_to menu_path, notice: notice and return
	  end
      else
	  # Check for note
	  if not payment_note.valid?
	      # Note required
	      redirect_to "/user_payments/approve", alert: "Error: could not re-submit UserPayment because a Note is required. Message: #{payment_note.errors.full_messages}" and return
	  end
	  # Bounce message back
	  user_payment.waiting_on_user_id=user_payment.to_user_id
	  # Save record
	  if user_payment.save
	      # Save note
	      payment_note.save!
	  end
	  # Notice
	  notice="Payment successfully re-submitted."
	  # Check if more user_payments
	  if user_payments.size > 0
	      # Redirect to approve
	      redirect_to "/user_payments/approve", notice: notice and return
	  else
	      # Redirect to menu
	      redirect_to menu_path, notice: notice and return
	  end
      end
  end
end

app/helpers/user_payments_helper.rb
module UserPaymentsHelper
end

app/views/user_payments/_form.html.haml
= form_for @user_payment do |f|
  - if @user_payment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_payment.errors.count, "error")} prohibited this user_payment from being saved:"
      %ul
        - @user_payment.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :to_user_id
    %br/
    = f.collection_select :to_user_id, @users, "id","user_name", prompt: '--'
  .field
    = f.label :amount
    %br/
    = f.text_field :amount
  .field
    = fields_for :payment_note do |pn|
      = pn.label :note
      %br/
      = pn.text_area :note, :rows => 2
  .actions
    = f.submit 'Save'

app/views/user_payments/approve.html.haml
%h1 UserPayments waiting for approval.
- @user_payments.each do |up|
  %b Date:
  = up.created_at
  %br
  %b From user:
  = up.from_user.user_name
  %br
  %b To user:
  = up.to_user.user_name
  %br
  %b amount:
  = number_to_currency(up.amount)
  - notes=up.payment_notes
  - if notes.size > 0
    %br
    %b Notes:
    %table{:border => 1, :cellpadding => 5, :cellspacing => 0}
      - notes.each do |note|
        %tr
          %td
            = note.user.user_name
          %td
            = note.created_at.strftime("%Y-%m-%d")
          %td
            = note.note
  = form_for :payment_approval, :url => "approve_payment" do |f|
    .field
      = f.label :note
      %br/
      = f.text_area :note, :rows => 2
    = hidden_field_tag 'user_payment_id',up.id
    .actions
      - if up.to_user_id == current_user.id
        = f.submit 'Approve'
        = f.submit 'Reject with Note'
      - else
        = f.submit 'Re-submit with note'

app/views/user_payments/edit.html.haml
%h1 Editing user_payment

= render 'form'

= link_to 'Show', @user_payment
\|
= link_to 'Back', user_payments_path

app/views/user_payments/index.html.haml
%h1 Listing user_payments

%table{:border => 1}
  %tr
    %th From user
    %th To user
    %th Amount
    %th Approved
    %th Approved date
    %th Notes
    %th

  - @user_payments.each do |user_payment|
    %tr
      %td= user_payment.from_user.user_name
      %td= user_payment.to_user.user_name
      %td= number_to_currency(user_payment.amount)
      %td= user_payment.approved
      %td= user_payment.approved_date
      %td= user_payment.payment_notes.size
      %td= link_to 'Show', user_payment

app/views/user_payments/new.html.haml
%h1 New user_payment

= render 'form'

app/views/user_payments/show.html.haml
%p#notice= notice

%p
  %b From user:
  = @user_payment.from_user.user_name
%p
  %b To user:
  = @user_payment.to_user.user_name
%p
  %b Amount:
  = number_to_currency(@user_payment.amount)
%p
  %b Approved:
  = @user_payment.approved
%p
  %b Approved date:
  = @user_payment.approved_date
- # Get Notes
- payment_notes=@user_payment.visible_payment_notes
- if payment_notes.size > 0
  %p
    %b Notes:
    %table{:border => 1}
      %tr
        %th Date
        %th User
        %th Note
        %th -
      - payment_notes.each do |note|
        %tr
          %td
            = note.created_at.strftime("%Y-%d-%m")
          %td
            = note.user.user_name
          %td
            = note.note
          %td
            - if note.can_be_destroyed?(current_user)
              = button_to 'Destroy', {:controller => :user_payments, :action => "remove_note", :id => note.id}, :method => :delete, confirm: 'Are you sure?'

%hr
%h3 Add Note
= form_for @payment_note, :url => "add_note" do |f|
  - if @payment_note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@payment_note.errors.count, "error")} prohibited this payment_note from being saved:"
      %ul
        - @payment_note.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :note
    %br/
    = f.text_area :note, :rows => 2
  = hidden_field_tag 'user_payment_id',@user_payment.id
  .actions
    = f.submit 'Save'
%hr

= link_to 'Edit', edit_user_payment_path(@user_payment)
\|
= link_to 'Destroy', @user_payment, method: :delete, data: { confirm: 'Are you sure?' }